# Generated by Django 5.2 on 2025-04-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='accuracy',
            field=models.CharField(choices=[('accurate', 'Yes, it was accurate'), ('partially_accurate', 'Partially accurate'), ('inaccurate', 'No, it was not accurate'), ('unsure', 'I am not sure')], max_length=20),
        ),
    ]
